name: Build

on: push

jobs:
    release:
        runs-on: ${{ matrix.os }}

        permissions:
            contents: write

        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]

        steps:
            - name: Check out Git repository
                uses: actions/checkout@v3

            - name: Set up Node
                uses: actions/setup-node@v3
                with:
                    node-version: 18

            - name: Set up Python
                uses: actions/setup-python@v4
                with:
                    python-version: 3.x

            - name: Install Dependencies
                run: npm ci
                shell: bash

            - name: Build
                env:
                    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: npm run dist
                shell: bash

            - name: Check if in 'dev' branch
                run: |
                    if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
                        echo "Creating pull request to merge 'dev' into 'master'"
                        git config --global user.name "GitHub Copilot"
                        git config --global user.email "copilot@github.com"
                        git checkout -b merge-dev-to-master
                        git push -u origin merge-dev-to-master
                        gh pr create --base master --head merge-dev-to-master --title "Merge 'dev' into 'master'" --body "Please review and approve this pull request."
                    else
                        echo "Not in 'dev' branch. Skipping pull request creation."
                    fi
                shell: bash
