name: Build

on:
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    build:
        runs-on: ${{ matrix.os }}
        if: github.event.pull_request.merged == false

        permissions:
          contents: write

        strategy:
          matrix:
            os: [macos-latest, ubuntu-latest, windows-latest]

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v3

            - name: Set up Node
              uses: actions/setup-node@v3
              with:
                node-version: 18

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: 3.x

            - name: Install Dependencies
              run: npm ci
              shell: bash

            - name: Build
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npm run dist
              shell: bash

            - name: Add comment
              run: gh pr comment "$NUMBER" --body "$BODY"
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                GH_REPO: ${{ github.repository }}
                NUMBER: ${{ github.event.pull_request.number }}
                BODY: >
                  :tada: Your pull request has been built successfully! :tada:
                  ------------------------------------------------
                  :white_check_mark: Pull request avaliable to review and merge.
